@extends('layouts.dashboard-volt')

@section('css')
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.5/css/dataTables.bootstrap5.min.css">

    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.3/dist/leaflet.css" integrity="sha256-kLaT2GOSpHechhsozzB+flnD+zUyjE2LlfWPgU04xyI=" crossorigin="" />

@endsection

@section('content')
    <div class="container">

        <div>
            <div class="row justify-content-center">
                <div class="col-md-10">
                    <div class="card">
                        <div class="card-header">
                            City
                        </div>
    
                        <div class="card-body" onLoad="javascript:init();">
                            <div id="map" style="height: 200px"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
    </div>
@endsection

@push('javascript')

    
<script src="https://unpkg.com/leaflet@1.9.3/dist/leaflet.js" integrity="sha256-WBkoXOwTeyKclOHuWtc+i2uENFpDZ9YPdf5Hf+D7ewM=" crossorigin=""></script>

    <script language="javascript">
        function init() {
            var map = new L.Map('map');

            L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
                attribution: '&copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors',
                maxZoom: 18
            }).addTo(map);
            map.attributionControl.setPrefix(''); // Don't show the 'Powered by Leaflet' text.

            var london = new L.LatLng(51.5056, -0.1213);
            map.setView(london, 13);

            // Define an array. This could be done in a seperate js file.
            // This tidy formatted section could even be generated by a server-side script
            // or fetched seperately as a jsonp request.
            var markers = [
                [-0.1244324, 51.5006728, "Big Ben"],
                [-0.2060772, 51.4744221, "Fulham"],
                [-0.119623, 51.503308, "London Eye"],
                [-0.1279688, 51.5077286, "Nelson's Column<br><a href=\"https://en.wikipedia.org/wiki/Nelson's_Column\">wp</a>"]
            ];

            //Loop through the markers array
            for (var i = 0; i < markers.length; i++) {

                var lon = markers[i][0];
                var lat = markers[i][1];
                var popupText = markers[i][2];

                var markerLocation = new L.LatLng(lat, lon);
                var marker = new L.Marker(markerLocation);
                map.addLayer(marker);

                marker.bindPopup(popupText);

            }

        }
    </script>
    


@endpush
